### ISSUE TITLE
Stuck in bed attempting to sleep during the day

### ISSUE THREAD

**Issue by alliumm** [DerpDerpling/NoBedExplosions#1]
After installing this mod I am able to get in bed during the day with no way to exit the bed. I need to alt + f4 or get kicked from the server to exit the bed in this state.

**Comment by AopoxlXil** [comment]
I am also having this issue, this bug occurs in no particular time of day or night. Like mentioned above, the only ways to get out of the bed is to close the game, or use commands.

**Comment by DerpDerpling** [comment]
Will look into it

**Comment by DerpDerpling** [comment]
fixed in [705d698](https://github.com/DerpDerpling/NoBedExplosions/commit/705d6984cc3e9318dde9690919ba47d3a7057e91)
